Repository DO-SOPT-SOPKATHON/Team1-Android, pull requests merged in 2023-11, with the labels that each got.

#4 [ADD/#3] 디자인 시스템 구축
  app/src/main/res/font/font_pretendard_bold.xml
  app/src/main/res/font/font_pretendard_regular.xml
  app/src/main/res/font/pretendard_bold.ttf
  app/src/main/res/font/pretendard_extra_bold.ttf
  app/src/main/res/font/pretendard_extra_light.ttf
  app/src/main/res/font/pretendard_light.ttf
  app/src/main/res/font/pretendard_medium.ttf
  app/src/main/res/font/pretendard_regular.ttf
  app/src/main/res/font/pretendard_semi_bold.ttf
  app/src/main/res/font/pretendard_thin.ttf
  app/src/main/res/layout/activity_mock.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/appearances.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
Labels: 상호

#11 [FEAT] 메인 화면 뷰 구현
  app/src/main/java/org/sopt/doSopkathon/presentation/main/MainActivity.kt
  app/src/main/java/org/sopt/doSopkathon/presentation/main/MainAdapter.kt
  app/src/main/java/org/sopt/doSopkathon/presentation/main/MainDialog.kt
  app/src/main/java/org/sopt/doSopkathon/presentation/main/MainViewHolder.kt
  app/src/main/res/drawable-xhdpi/ic_main_dialog_trash.png
  app/src/main/res/drawable-xhdpi/ic_main_logo.png
  app/src/main/res/drawable-xhdpi/ic_main_logo_text.png
  app/src/main/res/drawable-xhdpi/ic_main_trash.png
  app/src/main/res/drawable-xxhdpi/ic_main_dialog_trash.png
  app/src/main/res/drawable-xxhdpi/ic_main_logo.png
  app/src/main/res/drawable-xxhdpi/ic_main_logo_text.png
  app/src/main/res/drawable-xxhdpi/ic_main_trash.png
  app/src/main/res/drawable/ic_main_close.xml
  app/src/main/res/drawable/ic_main_dialog_text.xml
  app/src/main/res/drawable/ic_main_dialog_trash.png
  app/src/main/res/drawable/ic_main_fab.xml
  app/src/main/res/drawable/ic_main_logo.png
  app/src/main/res/drawable/ic_main_logo_text.png
  app/src/main/res/drawable/ic_main_top_text.xml
  app/src/main/res/drawable/ic_main_trash.png
  app/src/main/res/drawable/shape_black_fill_12_rect.xml
  app/src/main/res/drawable/shape_color_fill_8_rect.xml
  app/src/main/res/drawable/shape_fill_4_rect.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/dialog_main.xml
  app/src/main/res/layout/item_main.xml
  app/src/main/res/values/strings.xml
Labels: 명지

#12 [FEAT/#7] 걱정 작성 뷰 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/doSopkathon/data/datasource/Category.kt
  app/src/main/java/org/sopt/doSopkathon/data/mock/mockCategoryList.kt
  app/src/main/java/org/sopt/doSopkathon/presentation/write/WriteActivity.kt
  app/src/main/java/org/sopt/doSopkathon/presentation/write/WriteAdapter.kt
  app/src/main/java/org/sopt/doSopkathon/presentation/write/WriteViewHolder.kt
  app/src/main/res/drawable/img_write_background.png
  app/src/main/res/drawable/selector_btn_category_background.xml
  app/src/main/res/drawable/selector_btn_category_text.xml
  app/src/main/res/drawable/selector_btn_write_background.xml
  app/src/main/res/drawable/selector_btn_write_text.xml
  app/src/main/res/layout/activity_mock.xml
  app/src/main/res/layout/activity_write.xml
  app/src/main/res/layout/item_write_category.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: 상호

#13 [FEAT/#8] 걱정 목록뷰 구현
  app/src/main/java/org/sopt/doSopkathon/data/dataclass/List_DataClass.kt
  app/src/main/java/org/sopt/doSopkathon/data/mock/mockListList.kt
  app/src/main/java/org/sopt/doSopkathon/presentation/list/ListActivity.kt
  app/src/main/java/org/sopt/doSopkathon/presentation/list/ListAdapter.kt
  app/src/main/java/org/sopt/doSopkathon/presentation/list/ListViewHolder.kt
  app/src/main/res/drawable/img_expand_right_icon.png
  app/src/main/res/drawable/img_list_background.png
  app/src/main/res/drawable/img_list_top_background.png
  app/src/main/res/drawable/img_recycler_logo.png
  app/src/main/res/layout/activity_list.xml
  app/src/main/res/layout/item_list.xml
  app/src/main/res/values/strings.xml
Labels: 현지

#21 [FEAT/#15] 걱정 작성 뷰 서버 통신 구현
  app/build.gradle
  app/src/main/java/org/sopt/doSopkathon/api/ApiFactory.kt
  app/src/main/java/org/sopt/doSopkathon/api/ServicePool.kt
  app/src/main/java/org/sopt/doSopkathon/data/dataclass/Category.kt
  app/src/main/java/org/sopt/doSopkathon/data/datasource/WriteDataSource.kt
  app/src/main/java/org/sopt/doSopkathon/data/dto/request/WriteRequestDto.kt
  app/src/main/java/org/sopt/doSopkathon/data/dto/response/WriteResponseDto.kt
  app/src/main/java/org/sopt/doSopkathon/data/mock/mockCategoryList.kt
  app/src/main/java/org/sopt/doSopkathon/data/repository/WriteRepository.kt
  app/src/main/java/org/sopt/doSopkathon/data/service/WriteService.kt
  app/src/main/java/org/sopt/doSopkathon/presentation/write/WriteActivity.kt
  app/src/main/java/org/sopt/doSopkathon/presentation/write/WriteAdapter.kt
  app/src/main/java/org/sopt/doSopkathon/presentation/write/WriteViewHolder.kt
  app/src/main/java/org/sopt/doSopkathon/presentation/write/WriteViewModel.kt
  app/src/main/java/org/sopt/doSopkathon/util/ViewModelFactory.kt
  app/src/main/res/layout/dialog_main.xml
  app/src/main/res/raw/lottie_dialog_1.json
  app/src/main/res/raw/lottie_dialog_2.json
  app/src/main/res/values/strings.xml
Labels: 상호

#22 Feat/#16 list server
  app/src/main/java/org/sopt/doSopkathon/api/ServicePool.kt
  app/src/main/java/org/sopt/doSopkathon/data/dataclass/List_DataClass.kt
  app/src/main/java/org/sopt/doSopkathon/data/dto/request/ListRequestDto.kt
  app/src/main/java/org/sopt/doSopkathon/data/dto/response/ListResponseDto.kt
  app/src/main/java/org/sopt/doSopkathon/data/mock/mockListList.kt
  app/src/main/java/org/sopt/doSopkathon/data/service/ListService.kt
  app/src/main/java/org/sopt/doSopkathon/presentation/list/ListActivity.kt
  app/src/main/java/org/sopt/doSopkathon/presentation/list/ListAdapter.kt
  app/src/main/java/org/sopt/doSopkathon/presentation/list/ListViewHolder.kt
  app/src/main/res/drawable/img_list_expand_right_icon.png
  app/src/main/res/drawable/img_list_recycler_logo.png
  app/src/main/res/drawable/img_list_top_background.png
  app/src/main/res/drawable/img_list_top_small_box.png
  app/src/main/res/drawable/img_recycler_logo.png
  app/src/main/res/layout/activity_list.xml
  app/src/main/res/layout/item_list.xml
Labels: 현지

#30 [FIX/#27] 다이얼로그2 로티 구현
  app/src/main/res/layout/dialog_write.xml
Labels: 상호
